# Generated by Django 5.1.3 on 2024-11-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['enrollment_date']},
        ),
    ]
